enum RECENT_DATA_CATEGORY { DAILY, TRANSACTIONS, WORKOUTS }

enum HISTORY_CATEGORY { WORKOUTS, TRANSACTIONS }

enum SEND_MODAL_STEPS { CHOOSE_RECIPIENTS, SCAN_QR, AMOUNT_AND_CONFIRM }

enum RESET_PASSWORD_ERROR { WRONG_EMAIL, SERVER_ERROR }
