enum RECENT_DATA_CATEGORY { DAILY, TRANSACTIONS, WORKOUTS }

enum STEPS_AGGREGATION_TYPE { HOURLY, DAILY, MONTHLY }

enum STEPS_AGGREGATION_VALUE { TOTAL, MEAN }

enum ACTIVITY_TYPE { WALKING, RUNNING, BIKE_RIDING, SWIMMING }

enum HISTORY_CATEGORY { WORKOUTS, TRANSACTIONS }

enum SEND_MODAL_STEPS { CHOOSE_RECIPIENTS, SCAN_QR, AMOUNT_AND_CONFIRM }

enum RESET_PASSWORD_ERROR { WRONG_EMAIL, SERVER_ERROR }

enum PRODUCT_CATEGORY {
  UNKNOWN,
  FOOD,
  MEMBERSHIPS,
  EQUIPMENT,
  EVENTS,
  SUPPLEMENTS
}

enum TRANSACTION_TYPE { PURCHASE, SEND, RECEIVE, UNKNOWN }

enum SORTING_ORDER { ASCENDING, DESCENDING }

enum AUTH_METHOD { LOGIN, SIGNUP }

enum USER_DATA_INPUTS {
  NAME,
  SURNAME,
  EMAIL,
  PHONE_NUMBER,
  STREET,
  HOUSE_NUMBER,
  FLAT_NUMBER,
  POST_CODE,
  CITY,
  COMPANY_NAME,
  NIP
}
